apiVersion: apps/v1
kind: Deployment
metadata:
  name: felhohf
spec:
  selector:
    matchLabels:
      app: felhohf
  template:
    metadata:
      labels:
        app: felhohf
    spec:
      containers:
        - name: felhohf
          image: nbalint99/felhohf:{{ .Values.env.APP_VERSION }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          env:
          - name: MONGO_URI
            value: "mongodb://mongo:27017/carspics"
          readinessProbe:
            httpGet:
                path: /health
                port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
                path: /health
                port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
