apiVersion: v1
kind: PersistentVolume
metadata:
  name: other-mongo-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/other-mongo"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: other-mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
